name: cellpose_env
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - numpy
  - pytorch
  - torchvision
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - cudatoolkit=11.1  # adjust this to match your CUDA version
  - pip
  - pip:
    - cellpose
