name: splinedist
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
  # - nvidia
dependencies:
  - conda
  - python
  - cudatoolkit
  - pip=21
  - pandas
  # - mamba
  - pytest
  - tensorflow
  - tensorflow-gpu
  - tifffile
  - nbmake
  - scikit-image
  # - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - ipython
  - numpy
  - tqdm
  - scikit-learn
  - opencv
  - mesa-libgl-devel-cos7-x86_64
  - mesa-libgl-cos6-x86_64
  - libopencv
  # - py-opencv
  - ipython
  # - jupyter
  - nbconvert
  - matplotlib
  # - scipy
  - cudnn
  # - cxx-compilern
  # - gcc_linux-64
  # - nvcc_linux-64
  # - nccl
  # - nvidia-ml
  - pip:
    - stardist==0.6.2
    # - -e git+https://github.com/ctr26/splinedist.git#egg=splinedist
    - -e "../../splinedist/splinedist"